const ARB_SEPOLIA_EXCHANGE_ROUTER = "YOUR_EXCHANGE_ROUTER_ADDRESS";
const ARB_SEPOLIA_EXCHANGE_ROUTER_ABI = []; // Your ABI here
const ORDER_VAULT = "YOUR_ORDER_VAULT_ADDRESS";
const MARKET_TOKEN = "YOUR_MARKET_TOKEN_ADDRESS";
const INITIAL_COLLATERAL_TOKEN = "YOUR_COLLATERAL_TOKEN_ADDRESS";

export {
  ARB_SEPOLIA_EXCHANGE_ROUTER,
  ARB_SEPOLIA_EXCHANGE_ROUTER_ABI,
  ORDER_VAULT,
  MARKET_TOKEN,
  INITIAL_COLLATERAL_TOKEN,
};
